import type { LangCode } from "./i18n";

/** Interface copy for the Advanced Analytics screen (app/analytics.tsx).
 *  Scoped separately from the app-wide `strings()` table, same pattern as premium-copy.ts:
 *  one flat array per language keyed against `keys`, checked at runtime so a missing
 *  translation fails loudly instead of silently falling back to English.
 *
 *  Topic and subject names (e.g. "Verfassungsorgane") are never part of this file — they
 *  stay in German everywhere and must not be looked up here. See app/analytics.tsx. */
export type AnalyticsCopy = {
  title: string; outlookLabel: string; onTrack: string; buildScore: string; outlookNote: string;
  confidenceLow: string; confidenceMedium: string; confidenceHigh: string; confidenceLine: string;
  ofTotal: string; passMark: string; coverage: string; accuracy: string; accuracyNote: string;
  answers: string; answersNote: string; examAreas: string; masteredOf: string; reviewAll: string;
  practise20: string; areaActionA11y: string; nextBestMove: string; startBaseline: string;
  strengthenTopic: string; takeDiagnostic: string; wrongInTopic: string; strengthenMore: string;
  alreadyInZone: string; noEvidenceYet: string; startDrill: string; persistentErrors: string;
  needsAnotherLook: string; fixErrors: string; topicPriorities: string; weakestFirst: string;
  countOfTotal: string; practiceTopicA11y: string; statusNew: string; statusStrong: string;
  statusDeveloping: string; statusPriority: string; topicSummary: string; practiseArrow: string;
  showPrioritiesOnly: string; viewAllTopics: string;
};

const keys: (keyof AnalyticsCopy)[] = [
  "title", "outlookLabel", "onTrack", "buildScore", "outlookNote",
  "confidenceLow", "confidenceMedium", "confidenceHigh", "confidenceLine",
  "ofTotal", "passMark", "coverage", "accuracy", "accuracyNote",
  "answers", "answersNote", "examAreas", "masteredOf", "reviewAll",
  "practise20", "areaActionA11y", "nextBestMove", "startBaseline",
  "strengthenTopic", "takeDiagnostic", "wrongInTopic", "strengthenMore",
  "alreadyInZone", "noEvidenceYet", "startDrill", "persistentErrors",
  "needsAnotherLook", "fixErrors", "topicPriorities", "weakestFirst",
  "countOfTotal", "practiceTopicA11y", "statusNew", "statusStrong",
  "statusDeveloping", "statusPriority", "topicSummary", "practiseArrow",
  "showPrioritiesOnly", "viewAllTopics",
];

const rows: Record<LangCode, string[]> = {
  de: ["Bereitschaftsanalyse","Deine Prüfungsprognose","Du bist auf Kurs","Baue deine Punktzahl auf","Die Prognose basiert auf gefestigten Fragen, nicht nur auf den letzten Antworten.","Niedrig","Mittel","Hoch","{level} Sicherheit · {evidence}% Datenbasis","von {total}","Bestehensgrenze {mark} · Prognose {projected}","Abdeckung","Genauigkeit","alle Versuche","Antworten","geübt","Prüfungsbereiche","{mastery}/{questions} gefestigt","Alle ansehen","20 üben","{label} für diesen Prüfungsbereich","Dein nächster Schritt","Starte deine Ausgangsmessung","{topic} stärken","Mache einen adaptiven Diagnosetest","{wrong} falsche Antworten in diesem Thema.","Festige etwa {n} weitere Katalogfragen, um die Prognose-Bestehenszone zu erreichen.","Du bist bereits in der Prognose-Bestehenszone — festige jetzt schwache Themen.","Eine kurze gemischte Runde liefert der App genug Daten, um deine erste Priorität zu erkennen.","Gezielte Übung starten →","Wiederkehrende Fehler","braucht nochmal einen Blick","Diese Fehler beheben →","Themenprioritäten","Schwächste Themen zuerst","{visible} von {total}","{topic} üben","Neu","Stark","Im Aufbau","Priorität","{mastery} gefestigt · {attempted}/{questions} abgedeckt · {wrong} falsch","Üben →","Nur Prioritäten anzeigen ↑","Alle {n} Themen anzeigen ↓"],
  en: ["Readiness analytics","Your exam outlook","You’re on track","Build your score","Projection based on mastered questions, not just recent answers.","Low","Medium","High","{level} confidence · {evidence}% evidence","of {total}","pass mark {mark} · projected {projected}","Coverage","Accuracy","all attempts","Answers","practice","Exam areas","{mastery}/{questions} mastered","Review all","Practise 20","{label} this exam area","Your next best move","Start your baseline","Strengthen {topic}","Take an adaptive diagnostic","{wrong} wrong answers in this topic.","Strengthen about {n} more catalogue questions to enter the projected pass zone.","You are already in the projected pass zone—stabilize weak topics now.","A short mixed session gives the app enough evidence to identify your first priority.","Start focused drill →","Persistent errors","needs another look","Fix these errors →","Topic priorities","Weakest topics first","{visible} of {total}","Practise {topic}","New","Strong","Developing","Priority","{mastery} mastered · {attempted}/{questions} covered · {wrong} wrong","Practise →","Show priorities only ↑","View all {n} topics ↓"],
  tr: ["Hazırlık analizi","Sınav görünümün","Yolundasın","Puanını yükselt","Tahmin, sadece son cevaplara değil, kalıcı öğrenilen sorulara dayanır.","Düşük","Orta","Yüksek","{level} güven · %{evidence} kanıt","{total} üzerinden","geçme sınırı {mark} · tahmini {projected}","Kapsam","Doğruluk","tüm denemeler","Cevaplar","alıştırma","Sınav alanları","{questions} sorudan {mastery} kalıcı","Tümünü incele","20 soru çöz","Bu sınav alanı için {label}","Sıradaki en iyi adımın","Başlangıç ölçümünü yap","{topic} konusunu güçlendir","Uyarlanabilir bir tanı testi yap","Bu konuda {wrong} yanlış cevap var.","Tahmini geçme bölgesine girmek için katalogdan yaklaşık {n} soru daha güçlendir.","Zaten tahmini geçme bölgesindesin — şimdi zayıf konuları pekiştir.","Kısa, karışık bir oturum uygulamaya ilk önceliğini belirlemesi için yeterli veri sağlar.","Odaklı alıştırmayı başlat →","Sürekli tekrarlanan hatalar","tekrar bakılmalı","Bu hataları düzelt →","Konu öncelikleri","Önce en zayıf konular","{total} üzerinden {visible}","{topic} konusunu çalış","Yeni","Güçlü","Gelişiyor","Öncelikli","{mastery} kalıcı · {questions} sorudan {attempted} işlendi · {wrong} yanlış","Çalış →","Yalnızca öncelikleri göster ↑","{n} konunun tümünü göster ↓"],
  ru: ["Аналитика готовности","Прогноз по экзамену","Вы на верном пути","Наращивайте результат","Прогноз основан на закреплённых вопросах, а не только на последних ответах.","Низкая","Средняя","Высокая","{level} уверенность · {evidence}% данных","из {total}","проходной балл {mark} · прогноз {projected}","Охват","Точность","все попытки","Ответы","практика","Разделы экзамена","{mastery}/{questions} закреплено","Смотреть все","Практика 20","{label} — этот раздел экзамена","Ваш следующий шаг","Начните с исходной оценки","Закрепите тему «{topic}»","Пройдите адаптивную диагностику","{wrong} неверных ответов по этой теме.","Закрепите ещё около {n} вопросов из каталога, чтобы войти в зону прогнозируемого успеха.","Вы уже в зоне прогнозируемого успеха — теперь укрепляйте слабые темы.","Короткая смешанная сессия даст приложению достаточно данных, чтобы определить ваш первый приоритет.","Начать точечную тренировку →","Повторяющиеся ошибки","требует внимания","Исправить эти ошибки →","Приоритеты по темам","Сначала самые слабые темы","{visible} из {total}","Практика по теме «{topic}»","Новая","Сильная","В процессе","Приоритет","{mastery} закреплено · {attempted}/{questions} пройдено · {wrong} неверно","Практика →","Показать только приоритеты ↑","Показать все {n} тем ↓"],
  uk: ["Аналітика готовності","Прогноз на іспит","Ви на правильному шляху","Нарощуйте результат","Прогноз базується на закріплених питаннях, а не лише на останніх відповідях.","Низька","Середня","Висока","{level} впевненість · {evidence}% даних","з {total}","прохідний бал {mark} · прогноз {projected}","Охоплення","Точність","усі спроби","Відповіді","практика","Розділи іспиту","{mastery}/{questions} закріплено","Переглянути всі","Практика 20","{label} — цей розділ іспиту","Ваш наступний крок","Почніть із початкової оцінки","Закріпіть тему «{topic}»","Пройдіть адаптивну діагностику","{wrong} неправильних відповідей у цій темі.","Закріпіть ще приблизно {n} питань з каталогу, щоб увійти в зону прогнозованого успіху.","Ви вже в зоні прогнозованого успіху — тепер зміцнюйте слабкі теми.","Коротка змішана сесія дасть застосунку достатньо даних, щоб визначити ваш перший пріоритет.","Почати цілеспрямоване тренування →","Повторювані помилки","потребує уваги","Виправити ці помилки →","Пріоритети за темами","Спочатку найслабші теми","{visible} з {total}","Практика з теми «{topic}»","Нова","Сильна","У процесі","Пріоритет","{mastery} закріплено · {attempted}/{questions} пройдено · {wrong} неправильно","Практика →","Показати лише пріоритети ↑","Показати всі {n} тем ↓"],
  ar: ["تحليلات الاستعداد","توقعات امتحانك","أنت على المسار الصحيح","ارفع نتيجتك","التوقع مبني على الأسئلة المتقنة، وليس فقط على الإجابات الأخيرة.","منخفضة","متوسطة","عالية","ثقة {level} · {evidence}% أدلة","من {total}","حد النجاح {mark} · المتوقع {projected}","التغطية","الدقة","كل المحاولات","الإجابات","تدريب","مجالات الامتحان","{mastery}/{questions} متقَن","مراجعة الكل","تدريب 20","{label} لهذا المجال","خطوتك التالية الأفضل","ابدأ تقييمك الأساسي","عزّز {topic}","أجرِ اختبارًا تشخيصيًا تكيفيًا","{wrong} إجابات خاطئة في هذا الموضوع.","عزّز نحو {n} سؤالًا إضافيًا من الكتالوج للدخول في منطقة النجاح المتوقعة.","أنت بالفعل في منطقة النجاح المتوقعة — عزّز المواضيع الضعيفة الآن.","جلسة مختصرة ومتنوعة تمنح التطبيق أدلة كافية لتحديد أولويتك الأولى.","ابدأ تدريبًا مركزًا →","أخطاء متكررة","تحتاج مراجعة إضافية","أصلح هذه الأخطاء →","أولويات المواضيع","الأضعف أولًا","{visible} من {total}","تدرب على {topic}","جديد","قوي","قيد التطور","أولوية","{mastery} متقَن · {attempted}/{questions} مغطى · {wrong} خاطئ","تدرب →","إظهار الأولويات فقط ↑","عرض كل {n} موضوعًا ↓"],
  fr: ["Analyse de préparation","Votre projection d'examen","Vous êtes sur la bonne voie","Améliorez votre score","La projection se base sur les questions maîtrisées, pas seulement sur les réponses récentes.","Faible","Moyenne","Élevée","confiance {level} · {evidence}% de données","sur {total}","seuil de réussite {mark} · projection {projected}","Couverture","Précision","toutes tentatives","Réponses","entraînement","Domaines de l'examen","{mastery}/{questions} maîtrisées","Tout revoir","20 questions","{label} pour ce domaine d'examen","Votre prochaine priorité","Lancez votre évaluation initiale","Renforcez {topic}","Faites un diagnostic adaptatif","{wrong} réponses fausses sur ce thème.","Renforcez environ {n} questions supplémentaires du catalogue pour entrer dans la zone de réussite projetée.","Vous êtes déjà dans la zone de réussite projetée — stabilisez maintenant les thèmes faibles.","Une courte session mixte donne à l'application assez de données pour identifier votre première priorité.","Lancer un entraînement ciblé →","Erreurs persistantes","à revoir","Corriger ces erreurs →","Priorités par thème","Thèmes les plus faibles d'abord","{visible} sur {total}","S'entraîner sur {topic}","Nouveau","Solide","En progrès","Prioritaire","{mastery} maîtrisées · {attempted}/{questions} couvertes · {wrong} fausses","S'entraîner →","Afficher seulement les priorités ↑","Voir les {n} thèmes ↓"],
  hi: ["तैयारी विश्लेषण","आपकी परीक्षा संभावना","आप सही राह पर हैं","अपना स्कोर बढ़ाएँ","अनुमान केवल हाल के उत्तरों पर नहीं, बल्कि पक्के हो चुके प्रश्नों पर आधारित है।","कम","मध्यम","उच्च","{level} विश्वास · {evidence}% प्रमाण","{total} में से","उत्तीर्ण अंक {mark} · अनुमानित {projected}","कवरेज","सटीकता","सभी प्रयास","उत्तर","अभ्यास","परीक्षा क्षेत्र","{questions} में से {mastery} पक्के","सभी देखें","20 का अभ्यास करें","इस परीक्षा क्षेत्र के लिए {label}","आपका अगला सबसे अच्छा कदम","अपनी आधार जाँच शुरू करें","{topic} को मज़बूत करें","एक अनुकूली निदान परीक्षण लें","इस विषय में {wrong} गलत उत्तर हैं।","अनुमानित उत्तीर्ण क्षेत्र में पहुँचने के लिए सूची से लगभग {n} और प्रश्न मज़बूत करें।","आप पहले से ही अनुमानित उत्तीर्ण क्षेत्र में हैं — अब कमज़ोर विषयों को स्थिर करें।","एक छोटा मिश्रित सत्र ऐप को आपकी पहली प्राथमिकता पहचानने के लिए पर्याप्त प्रमाण देता है।","केंद्रित अभ्यास शुरू करें →","बार-बार होने वाली गलतियाँ","फिर से देखने की ज़रूरत है","ये गलतियाँ ठीक करें →","विषय प्राथमिकताएँ","पहले सबसे कमज़ोर विषय","{total} में से {visible}","{topic} का अभ्यास करें","नया","मज़बूत","विकासशील","प्राथमिकता","{mastery} पक्के · {questions} में से {attempted} पूर्ण · {wrong} गलत","अभ्यास करें →","केवल प्राथमिकताएँ दिखाएँ ↑","सभी {n} विषय दिखाएँ ↓"],
  pl: ["Analiza gotowości","Twoja prognoza egzaminu","Jesteś na dobrej drodze","Buduj swój wynik","Prognoza opiera się na opanowanych pytaniach, a nie tylko na ostatnich odpowiedziach.","Niska","Średnia","Wysoka","pewność: {level} · {evidence}% danych","z {total}","próg zaliczenia {mark} · prognoza {projected}","Pokrycie","Dokładność","wszystkie próby","Odpowiedzi","ćwiczenia","Obszary egzaminu","{mastery}/{questions} opanowane","Zobacz wszystkie","Ćwicz 20","{label} dla tego obszaru egzaminu","Twój następny najlepszy krok","Rozpocznij ocenę wstępną","Wzmocnij {topic}","Wykonaj adaptacyjny test diagnostyczny","{wrong} błędnych odpowiedzi w tym temacie.","Utrwal jeszcze około {n} pytań z katalogu, aby wejść w prognozowaną strefę zaliczenia.","Jesteś już w prognozowanej strefie zaliczenia — teraz utrwal słabe tematy.","Krótka mieszana sesja dostarczy aplikacji wystarczająco danych, aby określić Twój pierwszy priorytet.","Rozpocznij ukierunkowane ćwiczenie →","Powtarzające się błędy","wymaga ponownego spojrzenia","Popraw te błędy →","Priorytety tematów","Najpierw najsłabsze tematy","{visible} z {total}","Ćwicz {topic}","Nowy","Mocny","W trakcie","Priorytet","{mastery} opanowane · {attempted}/{questions} objęte · {wrong} błędne","Ćwicz →","Pokaż tylko priorytety ↑","Pokaż wszystkie {n} tematów ↓"],
  ro: ["Analiza pregătirii","Perspectiva ta la examen","Ești pe drumul cel bun","Îți crești scorul","Estimarea se bazează pe întrebările consolidate, nu doar pe răspunsurile recente.","Scăzută","Medie","Ridicată","încredere {level} · {evidence}% dovezi","din {total}","prag de promovare {mark} · estimat {projected}","Acoperire","Acuratețe","toate încercările","Răspunsuri","exersare","Domenii de examen","{mastery}/{questions} consolidate","Vezi tot","Exersează 20","{label} pentru acest domeniu de examen","Următorul tău pas","Începe evaluarea inițială","Consolidează {topic}","Susține un test diagnostic adaptiv","{wrong} răspunsuri greșite la acest subiect.","Consolidează încă aproximativ {n} întrebări din catalog pentru a intra în zona de promovare estimată.","Ești deja în zona de promovare estimată — stabilizează acum subiectele slabe.","O sesiune scurtă și mixtă oferă aplicației suficiente dovezi pentru a-ți identifica prima prioritate.","Începe exersarea țintită →","Greșeli persistente","necesită o nouă privire","Corectează aceste greșeli →","Priorități pe subiecte","Subiectele cele mai slabe primele","{visible} din {total}","Exersează {topic}","Nou","Puternic","În dezvoltare","Prioritar","{mastery} consolidate · {attempted}/{questions} acoperite · {wrong} greșite","Exersează →","Afișează doar prioritățile ↑","Vezi toate cele {n} subiecte ↓"],
  fa: ["تحلیل آمادگی","چشم‌انداز آزمون شما","در مسیر درست هستید","امتیازتان را بالا ببرید","پیش‌بینی بر اساس سؤال‌های تثبیت‌شده است، نه فقط پاسخ‌های اخیر.","کم","متوسط","زیاد","اطمینان {level} · {evidence}٪ شواهد","از {total}","حد قبولی {mark} · پیش‌بینی {projected}","پوشش","دقت","همهٔ تلاش‌ها","پاسخ‌ها","تمرین","بخش‌های آزمون","{mastery}/{questions} تثبیت‌شده","مشاهدهٔ همه","تمرین ۲۰ سؤال","{label} برای این بخش آزمون","بهترین قدم بعدی شما","ارزیابی اولیهٔ خود را شروع کنید","{topic} را تقویت کنید","یک آزمون تشخیصی تطبیقی بدهید","{wrong} پاسخ نادرست در این موضوع.","برای ورود به محدودهٔ قبولی پیش‌بینی‌شده، حدود {n} سؤال دیگر از فهرست را تقویت کنید.","شما هم‌اکنون در محدودهٔ قبولی پیش‌بینی‌شده هستید — اکنون موضوعات ضعیف را تثبیت کنید.","یک جلسهٔ کوتاه و ترکیبی شواهد کافی به برنامه می‌دهد تا اولین اولویت شما را مشخص کند.","شروع تمرین هدفمند →","خطاهای مکرر","نیاز به بررسی دوباره دارد","این خطاها را برطرف کنید →","اولویت‌های موضوعی","ابتدا ضعیف‌ترین موضوعات","{visible} از {total}","تمرین {topic}","جدید","قوی","در حال پیشرفت","در اولویت","{mastery} تثبیت‌شده · {attempted}/{questions} پوشش داده‌شده · {wrong} نادرست","تمرین →","فقط اولویت‌ها نمایش داده شود ↑","نمایش همهٔ {n} موضوع ↓"],
  ur: ["تیاری کا تجزیہ","آپ کے امتحان کا امکان","آپ درست راستے پر ہیں","اپنا اسکور بڑھائیں","یہ تخمینہ صرف حالیہ جوابات پر نہیں بلکہ پکے ہو چکے سوالات پر مبنی ہے۔","کم","درمیانہ","زیادہ","{level} اعتماد · {evidence}٪ شواہد","{total} میں سے","پاسنگ حد {mark} · متوقع {projected}","احاطہ","درستگی","تمام کوششیں","جوابات","مشق","امتحانی شعبے","{questions} میں سے {mastery} پکے","سب دیکھیں","20 کی مشق کریں","اس امتحانی شعبے کے لیے {label}","آپ کا اگلا بہترین قدم","اپنی ابتدائی جانچ شروع کریں","{topic} کو مضبوط کریں","ایک موافقتی تشخیصی ٹیسٹ لیں","اس موضوع میں {wrong} غلط جوابات ہیں۔","متوقع پاسنگ زون میں پہنچنے کے لیے فہرست سے تقریباً {n} مزید سوالات مضبوط کریں۔","آپ پہلے ہی متوقع پاسنگ زون میں ہیں — اب کمزور موضوعات کو مستحکم کریں۔","ایک مختصر مخلوط سیشن ایپ کو آپ کی پہلی ترجیح جاننے کے لیے کافی شواہد دیتا ہے۔","مرکوز مشق شروع کریں →","بار بار ہونے والی غلطیاں","دوبارہ دیکھنے کی ضرورت ہے","یہ غلطیاں درست کریں →","موضوعاتی ترجیحات","پہلے سب سے کمزور موضوعات","{total} میں سے {visible}","{topic} کی مشق کریں","نیا","مضبوط","ترقی پذیر","ترجیحی","{mastery} پکے · {questions} میں سے {attempted} احاطہ کیے گئے · {wrong} غلط","مشق کریں →","صرف ترجیحات دکھائیں ↑","تمام {n} موضوعات دکھائیں ↓"],
  sq: ["Analiza e gatishmërisë","Parashikimi i provimit tënd","Je në rrugën e duhur","Rrit rezultatin tënd","Parashikimi bazohet te pyetjet e përvetësuara, jo vetëm te përgjigjet e fundit.","E ulët","Mesatare","E lartë","besueshmëri {level} · {evidence}% të dhëna","nga {total}","kufiri kalues {mark} · parashikuar {projected}","Mbulimi","Saktësia","të gjitha përpjekjet","Përgjigje","ushtrim","Fushat e provimit","{mastery}/{questions} të përvetësuara","Shiko të gjitha","Ushtro 20","{label} për këtë fushë provimi","Hapi yt tjetër më i mirë","Nis vlerësimin fillestar","Forco {topic}","Bëj një test diagnostik adaptiv","{wrong} përgjigje të gabuara në këtë temë.","Forco rreth {n} pyetje të tjera nga katalogu për të hyrë në zonën e parashikuar kaluese.","Je tashmë në zonën e parashikuar kaluese — tani stabilizo temat e dobëta.","Një seancë e shkurtër e përzier i jep aplikacionit të dhëna të mjaftueshme për të identifikuar prioritetin tënd të parë.","Fillo ushtrimin e fokusuar →","Gabime të përsëritura","kërkon vëmendje sërish","Rregullo këto gabime →","Prioritetet e temave","Temat më të dobëta së pari","{visible} nga {total}","Ushtro {topic}","E re","E fortë","Në zhvillim","Prioritet","{mastery} të përvetësuara · {attempted}/{questions} mbuluara · {wrong} gabime","Ushtro →","Shfaq vetëm prioritetet ↑","Shfaq të gjitha {n} temat ↓"],
  bs: ["Analiza spremnosti","Vaša prognoza ispita","Na dobrom ste putu","Poboljšajte svoj rezultat","Prognoza se temelji na usvojenim pitanjima, ne samo na nedavnim odgovorima.","Niska","Srednja","Visoka","pouzdanost {level} · {evidence}% dokaza","od {total}","prag prolaza {mark} · prognoza {projected}","Pokrivenost","Tačnost","svi pokušaji","Odgovori","vježba","Područja ispita","{mastery}/{questions} usvojeno","Pregledaj sve","Vježbaj 20","{label} za ovo područje ispita","Vaš sljedeći najbolji korak","Započnite početnu procjenu","Ojačajte {topic}","Uradite adaptivni dijagnostički test","{wrong} pogrešnih odgovora u ovoj temi.","Utvrdite još oko {n} pitanja iz kataloga da uđete u prognoziranu zonu prolaza.","Već ste u prognoziranoj zoni prolaza — sada stabilizirajte slabe teme.","Kratka mješovita sesija daje aplikaciji dovoljno dokaza da odredi vaš prvi prioritet.","Pokreni ciljanu vježbu →","Ponavljajuće greške","treba ponovni pregled","Ispravi ove greške →","Prioriteti tema","Najslabije teme prve","{visible} od {total}","Vježbaj {topic}","Novo","Jako","U razvoju","Prioritet","{mastery} usvojeno · {attempted}/{questions} pokriveno · {wrong} pogrešno","Vježbaj →","Prikaži samo prioritete ↑","Prikaži svih {n} tema ↓"],
  bg: ["Анализ на готовността","Прогноза за изпита","На правилния път сте","Повишете резултата си","Прогнозата се базира на усвоените въпроси, а не само на последните отговори.","Ниска","Средна","Висока","{level} увереност · {evidence}% данни","от {total}","праг за успех {mark} · прогноза {projected}","Обхват","Точност","всички опити","Отговори","практика","Изпитни области","{mastery}/{questions} усвоени","Преглед на всички","Практика 20","{label} за тази изпитна област","Следващата ви най-добра стъпка","Започнете началната си оценка","Затвърдете {topic}","Направете адаптивен диагностичен тест","{wrong} грешни отговора в тази тема.","Затвърдете още около {n} въпроса от каталога, за да влезете в прогнозираната зона за успех.","Вече сте в прогнозираната зона за успех — сега стабилизирайте слабите теми.","Кратка смесена сесия дава на приложението достатъчно данни, за да определи първия ви приоритет.","Започнете целенасочена практика →","Повтарящи се грешки","нуждае се от повторен преглед","Коригирайте тези грешки →","Приоритети по теми","Най-слабите теми първо","{visible} от {total}","Практика по {topic}","Нова","Силна","В развитие","Приоритет","{mastery} усвоени · {attempted}/{questions} обхванати · {wrong} грешни","Практика →","Показвай само приоритетите ↑","Покажи всички {n} теми ↓"],
  it: ["Analisi di preparazione","La tua prospettiva d'esame","Sei sulla buona strada","Migliora il tuo punteggio","La proiezione si basa sulle domande consolidate, non solo sulle risposte recenti.","Bassa","Media","Alta","affidabilità {level} · {evidence}% di evidenza","su {total}","soglia di superamento {mark} · proiezione {projected}","Copertura","Precisione","tutti i tentativi","Risposte","esercitazione","Aree d'esame","{mastery}/{questions} consolidate","Rivedi tutto","Esercitati su 20","{label} per quest'area d'esame","La tua prossima mossa migliore","Avvia la tua valutazione iniziale","Rafforza {topic}","Fai un test diagnostico adattivo","{wrong} risposte errate in questo argomento.","Consolida altre {n} domande del catalogo circa per entrare nella zona di superamento prevista.","Sei già nella zona di superamento prevista — ora stabilizza gli argomenti deboli.","Una breve sessione mista dà all'app dati sufficienti per identificare la tua prima priorità.","Avvia un allenamento mirato →","Errori persistenti","da rivedere","Correggi questi errori →","Priorità per argomento","Prima gli argomenti più deboli","{visible} su {total}","Esercitati su {topic}","Nuovo","Forte","In sviluppo","Prioritario","{mastery} consolidate · {attempted}/{questions} coperte · {wrong} errate","Esercitati →","Mostra solo le priorità ↑","Mostra tutti i {n} argomenti ↓"],
  zh: ["备考分析","你的考试展望","进展顺利","继续提升分数","预测基于已掌握的题目，而不仅是最近的答题。","低","中","高","置信度：{level} · 证据 {evidence}%","/ {total}","及格线 {mark} · 预测 {projected}","覆盖率","正确率","所有作答","作答数","练习","考试领域","{mastery}/{questions} 已掌握","查看全部","练习 20 题","{label}此考试领域","你的下一个最佳行动","开始基线测试","巩固「{topic}」","进行自适应诊断测试","该主题有 {wrong} 道错题。","再巩固约 {n} 道题库题目即可进入预测及格区间。","你已进入预测及格区间——现在请巩固薄弱主题。","一次简短的混合练习即可为应用提供足够依据，识别你的首要优先事项。","开始专项练习 →","反复出错的题目","需要再看一遍","修正这些错误 →","主题优先级","薄弱主题优先","{visible} / {total}","练习「{topic}」","新","扎实","进步中","优先","{mastery} 已掌握 · {attempted}/{questions} 已覆盖 · {wrong} 错误","练习 →","仅显示优先项 ↑","查看全部 {n} 个主题 ↓"],
  el: ["Ανάλυση ετοιμότητας","Η προοπτική σου για την εξέταση","Είσαι σε καλό δρόμο","Βελτίωσε τη βαθμολογία σου","Η πρόβλεψη βασίζεται σε ερωτήσεις που έχεις κατακτήσει, όχι μόνο στις πρόσφατες απαντήσεις.","Χαμηλή","Μέτρια","Υψηλή","εμπιστοσύνη {level} · {evidence}% τεκμηρίωση","από {total}","όριο επιτυχίας {mark} · πρόβλεψη {projected}","Κάλυψη","Ακρίβεια","όλες οι προσπάθειες","Απαντήσεις","εξάσκηση","Ενότητες εξέτασης","{mastery}/{questions} κατακτημένες","Δες όλες","Εξάσκηση σε 20","{label} για αυτήν την ενότητα","Το επόμενο καλύτερο βήμα σου","Ξεκίνα την αρχική σου αξιολόγηση","Ενίσχυσε το «{topic}»","Κάνε ένα προσαρμοστικό διαγνωστικό τεστ","{wrong} λανθασμένες απαντήσεις σε αυτό το θέμα.","Ενίσχυσε περίπου {n} ακόμη ερωτήσεις από τον κατάλογο για να μπεις στη ζώνη προβλεπόμενης επιτυχίας.","Είσαι ήδη στη ζώνη προβλεπόμενης επιτυχίας — σταθεροποίησε τώρα τα αδύναμα θέματα.","Μια σύντομη μεικτή συνεδρία δίνει στην εφαρμογή αρκετά στοιχεία για να εντοπίσει την πρώτη σου προτεραιότητα.","Ξεκίνα στοχευμένη εξάσκηση →","Επίμονα λάθη","χρειάζεται νέο έλεγχο","Διόρθωσε αυτά τα λάθη →","Προτεραιότητες θεμάτων","Πρώτα τα πιο αδύναμα θέματα","{visible} από {total}","Εξάσκηση στο «{topic}»","Νέο","Δυνατό","Σε εξέλιξη","Προτεραιότητα","{mastery} κατακτημένες · {attempted}/{questions} καλυμμένες · {wrong} λανθασμένες","Εξάσκηση →","Εμφάνιση μόνο προτεραιοτήτων ↑","Εμφάνιση και των {n} θεμάτων ↓"],
};

export function analyticsCopy(lang: LangCode): AnalyticsCopy {
  const row = rows[lang];
  if (!row || row.length !== keys.length) throw new Error(`Incomplete Analytics copy for ${lang}`);
  return Object.fromEntries(keys.map((key, i) => [key, row[i]])) as AnalyticsCopy;
}
