import type { LangCode } from "./i18n";

export type AuthCopy = {
  forgot: string; resetTitle: string; resetIntro: string; validEmail: string;
  connect: string; checkEmail: string; sendLink: string; back: string;
  newTitle: string; invalidLink: string; validating: string; enterNew: string;
  newPassword: string; confirmPassword: string; updatePassword: string;
  passwordMin: string; mismatch: string; resend: string; confirmationSent: string;
};

const keys: (keyof AuthCopy)[] = [
  "forgot", "resetTitle", "resetIntro", "validEmail", "connect", "checkEmail", "sendLink", "back",
  "newTitle", "invalidLink", "validating", "enterNew", "newPassword", "confirmPassword", "updatePassword",
  "passwordMin", "mismatch", "resend", "confirmationSent",
];

const rows: Partial<Record<LangCode, string[]>> = {
  en: ["Forgot password?", "Reset password", "Enter your account email and we’ll send you a password-reset link.", "Please enter a valid email address.", "Unable to connect. Check your internet connection and try again.", "Check your email and open the reset link on this device.", "Send reset link", "Back to login", "Choose a new password", "This reset link is invalid or has expired.", "Validating your reset link…", "Enter a new password for your account.", "New password", "Confirm new password", "Update password", "Password must be at least 6 characters.", "Passwords do not match.", "Resend confirmation email", "Confirmation email sent. Check your inbox and spam folder."],
  de: ["Passwort vergessen?", "Passwort zurücksetzen", "Gib die E-Mail-Adresse deines Kontos ein. Wir senden dir einen Link zum Zurücksetzen.", "Bitte gib eine gültige E-Mail-Adresse ein.", "Verbindung nicht möglich. Prüfe deine Internetverbindung und versuche es erneut.", "Prüfe deine E-Mails und öffne den Link auf diesem Gerät.", "Link senden", "Zurück zur Anmeldung", "Neues Passwort wählen", "Dieser Link ist ungültig oder abgelaufen.", "Link wird geprüft…", "Gib ein neues Passwort für dein Konto ein.", "Neues Passwort", "Neues Passwort bestätigen", "Passwort aktualisieren", "Das Passwort muss mindestens 6 Zeichen lang sein.", "Die Passwörter stimmen nicht überein.", "Bestätigungs-E-Mail erneut senden", "Bestätigungs-E-Mail gesendet. Prüfe auch deinen Spam-Ordner."],
  tr: ["Şifrenizi mi unuttunuz?", "Şifreyi sıfırla", "Hesap e-postanızı girin; size bir sıfırlama bağlantısı gönderelim.", "Lütfen geçerli bir e-posta adresi girin.", "Bağlanılamadı. İnternet bağlantınızı kontrol edip tekrar deneyin.", "E-postanızı kontrol edin ve sıfırlama bağlantısını bu cihazda açın.", "Sıfırlama bağlantısı gönder", "Girişe dön", "Yeni şifre seç", "Bu bağlantı geçersiz veya süresi dolmuş.", "Bağlantı doğrulanıyor…", "Hesabınız için yeni bir şifre girin.", "Yeni şifre", "Yeni şifreyi onayla", "Şifreyi güncelle", "Şifre en az 6 karakter olmalıdır.", "Şifreler eşleşmiyor.", "Onay e-postasını yeniden gönder", "Onay e-postası gönderildi. Gelen kutunuzu ve spam klasörünü kontrol edin."],
  ru: ["Забыли пароль?", "Сбросить пароль", "Введите электронную почту аккаунта, и мы отправим ссылку для сброса.", "Введите действительный адрес электронной почты.", "Не удалось подключиться. Проверьте интернет и повторите попытку.", "Проверьте почту и откройте ссылку на этом устройстве.", "Отправить ссылку", "Вернуться ко входу", "Выберите новый пароль", "Ссылка недействительна или срок её действия истёк.", "Проверяем ссылку…", "Введите новый пароль для аккаунта.", "Новый пароль", "Подтвердите новый пароль", "Обновить пароль", "Пароль должен содержать не менее 6 символов.", "Пароли не совпадают.", "Отправить письмо подтверждения повторно", "Письмо отправлено. Проверьте входящие и папку спама."],
  uk: ["Забули пароль?", "Скинути пароль", "Введіть електронну адресу облікового запису, і ми надішлемо посилання для скидання.", "Введіть дійсну електронну адресу.", "Не вдалося підключитися. Перевірте інтернет і повторіть спробу.", "Перевірте пошту та відкрийте посилання на цьому пристрої.", "Надіслати посилання", "Назад до входу", "Виберіть новий пароль", "Посилання недійсне або прострочене.", "Перевіряємо посилання…", "Введіть новий пароль для облікового запису.", "Новий пароль", "Підтвердьте новий пароль", "Оновити пароль", "Пароль має містити щонайменше 6 символів.", "Паролі не збігаються.", "Надіслати лист підтвердження повторно", "Лист надіслано. Перевірте вхідні та спам."],
  ar: ["هل نسيت كلمة المرور؟", "إعادة تعيين كلمة المرور", "أدخل بريد حسابك وسنرسل لك رابط إعادة التعيين.", "يرجى إدخال بريد إلكتروني صالح.", "تعذر الاتصال. تحقق من الإنترنت وحاول مرة أخرى.", "تحقق من بريدك وافتح رابط إعادة التعيين على هذا الجهاز.", "إرسال رابط إعادة التعيين", "العودة إلى تسجيل الدخول", "اختر كلمة مرور جديدة", "رابط إعادة التعيين غير صالح أو منتهي الصلاحية.", "جارٍ التحقق من الرابط…", "أدخل كلمة مرور جديدة لحسابك.", "كلمة المرور الجديدة", "تأكيد كلمة المرور الجديدة", "تحديث كلمة المرور", "يجب ألا تقل كلمة المرور عن 6 أحرف.", "كلمتا المرور غير متطابقتين.", "إعادة إرسال رسالة التأكيد", "تم إرسال رسالة التأكيد. تحقق من الوارد والبريد المزعج."],
  fr: ["Mot de passe oublié ?", "Réinitialiser le mot de passe", "Saisissez l’e-mail du compte et nous vous enverrons un lien de réinitialisation.", "Veuillez saisir une adresse e-mail valide.", "Connexion impossible. Vérifiez votre connexion Internet et réessayez.", "Consultez vos e-mails et ouvrez le lien sur cet appareil.", "Envoyer le lien", "Retour à la connexion", "Choisir un nouveau mot de passe", "Ce lien est invalide ou a expiré.", "Validation du lien…", "Saisissez un nouveau mot de passe pour votre compte.", "Nouveau mot de passe", "Confirmer le nouveau mot de passe", "Mettre à jour le mot de passe", "Le mot de passe doit comporter au moins 6 caractères.", "Les mots de passe ne correspondent pas.", "Renvoyer l’e-mail de confirmation", "E-mail envoyé. Vérifiez votre boîte de réception et les indésirables."],
  hi: ["पासवर्ड भूल गए?", "पासवर्ड रीसेट करें", "अपने खाते का ईमेल दर्ज करें; हम रीसेट लिंक भेजेंगे।", "कृपया मान्य ईमेल पता दर्ज करें।", "कनेक्ट नहीं हो सका। इंटरनेट जाँचें और फिर प्रयास करें।", "अपना ईमेल देखें और रीसेट लिंक इसी डिवाइस पर खोलें।", "रीसेट लिंक भेजें", "लॉगिन पर वापस जाएँ", "नया पासवर्ड चुनें", "यह रीसेट लिंक अमान्य है या समाप्त हो चुका है।", "लिंक की जाँच हो रही है…", "अपने खाते के लिए नया पासवर्ड दर्ज करें।", "नया पासवर्ड", "नए पासवर्ड की पुष्टि करें", "पासवर्ड अपडेट करें", "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।", "पासवर्ड मेल नहीं खाते।", "पुष्टि ईमेल फिर भेजें", "पुष्टि ईमेल भेज दिया गया। इनबॉक्स और स्पैम देखें।"],
  pl: ["Nie pamiętasz hasła?", "Zresetuj hasło", "Wpisz e-mail konta, a wyślemy link do zresetowania hasła.", "Wpisz prawidłowy adres e-mail.", "Nie można się połączyć. Sprawdź internet i spróbuj ponownie.", "Sprawdź pocztę i otwórz link na tym urządzeniu.", "Wyślij link", "Wróć do logowania", "Wybierz nowe hasło", "Ten link jest nieprawidłowy lub wygasł.", "Sprawdzanie linku…", "Wpisz nowe hasło do konta.", "Nowe hasło", "Potwierdź nowe hasło", "Zaktualizuj hasło", "Hasło musi mieć co najmniej 6 znaków.", "Hasła nie są takie same.", "Wyślij ponownie e-mail potwierdzający", "E-mail wysłany. Sprawdź skrzynkę odbiorczą i spam."],
  ro: ["Ați uitat parola?", "Resetați parola", "Introduceți e-mailul contului și vă vom trimite un link de resetare.", "Introduceți o adresă de e-mail validă.", "Conectarea nu a reușit. Verificați internetul și încercați din nou.", "Verificați e-mailul și deschideți linkul pe acest dispozitiv.", "Trimiteți linkul", "Înapoi la autentificare", "Alegeți o parolă nouă", "Linkul este nevalid sau a expirat.", "Se verifică linkul…", "Introduceți o parolă nouă pentru cont.", "Parolă nouă", "Confirmați parola nouă", "Actualizați parola", "Parola trebuie să aibă cel puțin 6 caractere.", "Parolele nu coincid.", "Retrimiteți e-mailul de confirmare", "E-mail trimis. Verificați mesajele primite și spamul."],
  fa: ["رمز عبور را فراموش کرده‌اید؟", "بازنشانی رمز عبور", "ایمیل حساب را وارد کنید تا پیوند بازنشانی ارسال شود.", "لطفاً یک ایمیل معتبر وارد کنید.", "اتصال ممکن نشد. اینترنت را بررسی و دوباره تلاش کنید.", "ایمیل خود را بررسی و پیوند را در همین دستگاه باز کنید.", "ارسال پیوند بازنشانی", "بازگشت به ورود", "رمز عبور جدید انتخاب کنید", "این پیوند نامعتبر یا منقضی شده است.", "در حال بررسی پیوند…", "رمز عبور جدید حساب را وارد کنید.", "رمز عبور جدید", "تأیید رمز عبور جدید", "به‌روزرسانی رمز عبور", "رمز عبور باید حداقل ۶ نویسه باشد.", "رمزهای عبور یکسان نیستند.", "ارسال دوباره ایمیل تأیید", "ایمیل تأیید ارسال شد. صندوق ورودی و هرزنامه را بررسی کنید."],
  ur: ["پاس ورڈ بھول گئے؟", "پاس ورڈ ری سیٹ کریں", "اکاؤنٹ کا ای میل درج کریں، ہم ری سیٹ لنک بھیجیں گے۔", "درست ای میل پتہ درج کریں۔", "کنکشن نہیں ہو سکا۔ انٹرنیٹ چیک کر کے دوبارہ کوشش کریں۔", "ای میل دیکھیں اور ری سیٹ لنک اسی ڈیوائس پر کھولیں۔", "ری سیٹ لنک بھیجیں", "لاگ ان پر واپس جائیں", "نیا پاس ورڈ منتخب کریں", "یہ لنک غلط ہے یا اس کی مدت ختم ہو چکی ہے۔", "لنک کی جانچ ہو رہی ہے…", "اپنے اکاؤنٹ کے لیے نیا پاس ورڈ درج کریں۔", "نیا پاس ورڈ", "نئے پاس ورڈ کی تصدیق", "پاس ورڈ اپ ڈیٹ کریں", "پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے۔", "پاس ورڈ ایک جیسے نہیں ہیں۔", "تصدیقی ای میل دوبارہ بھیجیں", "تصدیقی ای میل بھیج دی گئی۔ ان باکس اور اسپیم دیکھیں۔"],
};

export function authCopy(lang: LangCode): AuthCopy {
  const row = rows[lang] ?? rows.en!;
  return Object.fromEntries(keys.map((key, index) => [key, row[index]])) as AuthCopy;
}
