import type { LangCode } from "./i18n";

export type FeatureCopy = {
  advertisement: string; testBanner: string; adTestTitle: string; adTestBody: string; closeContinue: string;
  premium: string; premiumActive: string; closeMenu: string; menu: string;
  cloudUnavailable: string; showPassword: string; hidePassword: string;
  deleteAccountTitle: string; deleteAccountMessage: string; deleteAccountAction: string;
  signOutTitle: string; signOutMessage: string;
};

const keys: (keyof FeatureCopy)[] = [
  "advertisement", "testBanner", "adTestTitle", "adTestBody", "closeContinue",
  "premium", "premiumActive", "closeMenu", "menu", "cloudUnavailable", "showPassword", "hidePassword",
  "deleteAccountTitle", "deleteAccountMessage", "deleteAccountAction", "signOutTitle", "signOutMessage",
];

const rows: Record<LangCode, string[]> = {
  de: ["WERBUNG", "Testplatz für Bannerwerbung", "Test für Vollbildwerbung", "Dieser Platzhalter wird später durch eine echte Vollbildwerbung ersetzt.", "Schließen und fortfahren", "Premium", "Premium aktiv", "Menü schließen", "Menü", "Die Cloud-Anmeldung ist in diesem Build nicht eingerichtet.", "Anzeigen", "Ausblenden", "Konto löschen?", "Dein Cloud-Konto, synchronisierte Daten und alle Daten auf diesem Gerät werden dauerhaft gelöscht.", "Konto löschen", "Abmelden und dieses Gerät zurücksetzen?", "Alle Fortschritte und Einstellungen auf diesem Gerät werden gelöscht. Deine synchronisierten Cloud-Daten bleiben erhalten."],
  en: ["ADVERTISEMENT", "Test banner placement", "Full-screen ad test", "This placeholder will be replaced by a real interstitial ad.", "Close and continue", "Premium", "Premium active", "Close menu", "Menu", "Cloud sign-in is not configured for this build.", "Show", "Hide", "Delete account?", "Your cloud account, synced data, and all data stored on this device will be permanently deleted.", "Delete account", "Sign out and reset this device?", "All progress and preferences stored on this device will be removed. Your synced cloud progress will remain."],
  tr: ["REKLAM", "Test banner alanı", "Tam ekran reklam testi", "Bu yer tutucu daha sonra gerçek bir geçiş reklamıyla değiştirilecektir.", "Kapat ve devam et", "Premium", "Premium etkin", "Menüyü kapat", "Menü", "Bulut oturumu bu sürüm için yapılandırılmamış.", "Göster", "Gizle", "Hesap silinsin mi?", "Bulut hesabınız, eşitlenen verileriniz ve bu cihazdaki tüm veriler kalıcı olarak silinecek.", "Hesabı sil", "Çıkış yapıp bu cihaz sıfırlansın mı?", "Bu cihazdaki tüm ilerleme ve tercihler silinecek. Eşitlenen bulut ilerlemeniz korunacak."],
  ru: ["РЕКЛАМА", "Тестовое место для баннера", "Тест полноэкранной рекламы", "Позже здесь будет показана настоящая межстраничная реклама.", "Закрыть и продолжить", "Премиум", "Премиум активен", "Закрыть меню", "Меню", "Облачный вход не настроен для этой сборки.", "Показать", "Скрыть", "Удалить аккаунт?", "Облачный аккаунт, синхронизированные данные и все данные на этом устройстве будут удалены безвозвратно.", "Удалить аккаунт", "Выйти и сбросить это устройство?", "Все данные о прогрессе и настройки на этом устройстве будут удалены. Синхронизированный прогресс в облаке сохранится."],
  uk: ["РЕКЛАМА", "Тестове місце для банера", "Тест повноекранної реклами", "Пізніше цей заповнювач буде замінено справжньою міжсторінковою рекламою.", "Закрити й продовжити", "Преміум", "Преміум активний", "Закрити меню", "Меню", "Хмарний вхід не налаштовано для цієї збірки.", "Показати", "Сховати", "Видалити обліковий запис?", "Ваш хмарний обліковий запис, синхронізовані дані та всі дані на цьому пристрої буде видалено назавжди.", "Видалити обліковий запис", "Вийти й скинути цей пристрій?", "Увесь прогрес і налаштування на цьому пристрої буде видалено. Синхронізований хмарний прогрес збережеться."],
  ar: ["إعلان", "موضع تجريبي لإعلان بانر", "اختبار إعلان بملء الشاشة", "سيُستبدل هذا العنصر لاحقًا بإعلان بيني حقيقي.", "إغلاق ومتابعة", "بريميوم", "بريميوم مفعّل", "إغلاق القائمة", "القائمة", "تسجيل الدخول السحابي غير مُعدّ في هذا الإصدار.", "إظهار", "إخفاء", "حذف الحساب؟", "سيُحذف حسابك السحابي والبيانات المتزامنة وجميع البيانات الموجودة على هذا الجهاز نهائيًا.", "حذف الحساب", "تسجيل الخروج وإعادة ضبط هذا الجهاز؟", "ستُحذف كل بيانات التقدم والتفضيلات على هذا الجهاز، مع بقاء التقدم المتزامن في السحابة."],
  fr: ["PUBLICITÉ", "Emplacement test de bannière", "Test de publicité plein écran", "Cet emplacement sera remplacé ultérieurement par une véritable publicité interstitielle.", "Fermer et continuer", "Premium", "Premium actif", "Fermer le menu", "Menu", "La connexion au cloud n'est pas configurée pour cette version.", "Afficher", "Masquer", "Supprimer le compte ?", "Votre compte cloud, vos données synchronisées et toutes les données de cet appareil seront définitivement supprimés.", "Supprimer le compte", "Se déconnecter et réinitialiser cet appareil ?", "La progression et les préférences de cet appareil seront supprimées. Votre progression synchronisée dans le cloud sera conservée."],
  hi: ["विज्ञापन", "परीक्षण बैनर स्थान", "पूर्ण-स्क्रीन विज्ञापन परीक्षण", "यह स्थान बाद में वास्तविक इंटरस्टिशियल विज्ञापन से बदला जाएगा।", "बंद करें और जारी रखें", "प्रीमियम", "प्रीमियम सक्रिय", "मेन्यू बंद करें", "मेन्यू", "इस बिल्ड में क्लाउड लॉगिन कॉन्फ़िगर नहीं है।", "दिखाएँ", "छिपाएँ", "खाता हटाएँ?", "आपका क्लाउड खाता, सिंक किया गया डेटा और इस डिवाइस का सारा डेटा स्थायी रूप से हटा दिया जाएगा।", "खाता हटाएँ", "लॉग आउट करके यह डिवाइस रीसेट करें?", "इस डिवाइस की सारी प्रगति और प्राथमिकताएँ हट जाएँगी। सिंक की गई क्लाउड प्रगति बनी रहेगी।"],
  pl: ["REKLAMA", "Testowe miejsce na baner", "Test reklamy pełnoekranowej", "Ten element zostanie później zastąpiony prawdziwą reklamą pełnoekranową.", "Zamknij i kontynuuj", "Premium", "Premium aktywne", "Zamknij menu", "Menu", "Logowanie w chmurze nie jest skonfigurowane w tej wersji.", "Pokaż", "Ukryj", "Usunąć konto?", "Twoje konto w chmurze, zsynchronizowane dane i wszystkie dane na tym urządzeniu zostaną trwale usunięte.", "Usuń konto", "Wylogować się i zresetować urządzenie?", "Cały postęp i ustawienia na tym urządzeniu zostaną usunięte. Zsynchronizowany postęp w chmurze pozostanie."],
  ro: ["PUBLICITATE", "Spațiu de test pentru banner", "Test de reclamă pe tot ecranul", "Acest substituent va fi înlocuit ulterior cu o reclamă interstițială reală.", "Închideți și continuați", "Premium", "Premium activ", "Închideți meniul", "Meniu", "Autentificarea în cloud nu este configurată pentru această versiune.", "Afișați", "Ascundeți", "Ștergeți contul?", "Contul cloud, datele sincronizate și toate datele de pe acest dispozitiv vor fi șterse definitiv.", "Ștergeți contul", "Vă deconectați și resetați dispozitivul?", "Tot progresul și preferințele de pe acest dispozitiv vor fi șterse. Progresul sincronizat în cloud va rămâne."],
  fa: ["تبلیغ", "جایگاه آزمایشی بنر", "آزمایش تبلیغ تمام‌صفحه", "این جای‌نگهدار بعداً با یک تبلیغ بینابینی واقعی جایگزین می‌شود.", "بستن و ادامه", "پریمیوم", "پریمیوم فعال است", "بستن منو", "منو", "ورود ابری برای این نسخه پیکربندی نشده است.", "نمایش", "پنهان کردن", "حساب حذف شود؟", "حساب ابری، داده‌های همگام‌شده و همه داده‌های ذخیره‌شده در این دستگاه برای همیشه حذف می‌شوند.", "حذف حساب", "خروج و بازنشانی این دستگاه؟", "همه پیشرفت‌ها و تنظیمات این دستگاه حذف می‌شوند. پیشرفت همگام‌شده در فضای ابری باقی می‌ماند."],
  ur: ["اشتہار", "آزمائشی بینر کی جگہ", "فل اسکرین اشتہار کا ٹیسٹ", "یہ عارضی جگہ بعد میں حقیقی انٹرسٹیشل اشتہار سے بدل دی جائے گی۔", "بند کریں اور جاری رکھیں", "پریمیم", "پریمیم فعال ہے", "مینو بند کریں", "مینو", "اس بلڈ میں کلاؤڈ لاگ اِن ترتیب نہیں دیا گیا۔", "دکھائیں", "چھپائیں", "اکاؤنٹ حذف کریں؟", "آپ کا کلاؤڈ اکاؤنٹ، ہم آہنگ ڈیٹا اور اس ڈیوائس کا تمام ڈیٹا مستقل طور پر حذف ہو جائے گا۔", "اکاؤنٹ حذف کریں", "لاگ آؤٹ کر کے یہ ڈیوائس ری سیٹ کریں؟", "اس ڈیوائس کی تمام پیش رفت اور ترجیحات حذف ہو جائیں گی۔ کلاؤڈ میں ہم آہنگ پیش رفت برقرار رہے گی۔"],
  sq: ["REKLAMË", "Vend testues për banderolë", "Test reklame me ekran të plotë", "Ky element do të zëvendësohet më vonë me një reklamë të vërtetë ndërmjetëse.", "Mbyll dhe vazhdo", "Premium", "Premium aktiv", "Mbyll menynë", "Menyja", "Hyrja në renë kompjuterike nuk është konfiguruar për këtë version.", "Shfaq", "Fshih", "Të fshihet llogaria?", "Llogaria në re, të dhënat e sinkronizuara dhe të gjitha të dhënat në këtë pajisje do të fshihen përgjithmonë.", "Fshi llogarinë", "Të dilni dhe të rivendosni pajisjen?", "I gjithë përparimi dhe preferencat në këtë pajisje do të fshihen. Përparimi i sinkronizuar në re do të ruhet."],
  bs: ["OGLAS", "Testno mjesto za baner", "Test oglasa preko cijelog ekrana", "Ovo probno mjesto će kasnije zamijeniti pravi međuprostorni oglas.", "Zatvori i nastavi", "Premium", "Premium je aktivan", "Zatvori meni", "Meni", "Prijava u oblak nije podešena za ovu verziju.", "Prikaži", "Sakrij", "Izbrisati račun?", "Vaš račun u oblaku, sinhronizovani podaci i svi podaci na ovom uređaju bit će trajno izbrisani.", "Izbriši račun", "Odjaviti se i resetovati uređaj?", "Sav napredak i postavke na ovom uređaju bit će izbrisani. Sinhronizovani napredak u oblaku će ostati."],
  bg: ["РЕКЛАМА", "Тестово място за банер", "Тест на реклама на цял екран", "Този заместител по-късно ще бъде заменен с истинска междинна реклама.", "Затваряне и продължаване", "Премиум", "Премиум е активен", "Затваряне на менюто", "Меню", "Входът в облака не е конфигуриран за тази версия.", "Показване", "Скриване", "Изтриване на профила?", "Облачният ви профил, синхронизираните данни и всички данни на това устройство ще бъдат изтрити завинаги.", "Изтриване на профила", "Изход и нулиране на устройството?", "Целият напредък и настройки на това устройство ще бъдат изтрити. Синхронизираният напредък в облака ще остане."],
  it: ["PUBBLICITÀ", "Spazio di prova per banner", "Test pubblicitario a schermo intero", "Questo segnaposto verrà sostituito in seguito da una vera pubblicità interstiziale.", "Chiudi e continua", "Premium", "Premium attivo", "Chiudi menu", "Menu", "L'accesso cloud non è configurato per questa versione.", "Mostra", "Nascondi", "Eliminare l'account?", "L'account cloud, i dati sincronizzati e tutti i dati su questo dispositivo verranno eliminati definitivamente.", "Elimina account", "Disconnettersi e ripristinare il dispositivo?", "Tutti i progressi e le preferenze su questo dispositivo verranno eliminati. I progressi sincronizzati nel cloud rimarranno."],
  zh: ["广告", "测试横幅广告位", "全屏广告测试", "此占位内容稍后将替换为真正的插页式广告。", "关闭并继续", "高级版", "高级版已启用", "关闭菜单", "菜单", "此版本尚未配置云端登录。", "显示", "隐藏", "删除账户？", "您的云端账户、同步数据以及此设备上的全部数据都将被永久删除。", "删除账户", "退出登录并重置此设备？", "此设备上的全部进度和设置将被删除，已同步到云端的进度会保留。"],
  el: ["ΔΙΑΦΗΜΙΣΗ", "Δοκιμαστική θέση banner", "Δοκιμή διαφήμισης πλήρους οθόνης", "Αυτό το προσωρινό στοιχείο θα αντικατασταθεί αργότερα από πραγματική παρενθετική διαφήμιση.", "Κλείσιμο και συνέχεια", "Premium", "Το Premium είναι ενεργό", "Κλείσιμο μενού", "Μενού", "Η σύνδεση στο cloud δεν έχει ρυθμιστεί για αυτή την έκδοση.", "Εμφάνιση", "Απόκρυψη", "Διαγραφή λογαριασμού;", "Ο λογαριασμός cloud, τα συγχρονισμένα δεδομένα και όλα τα δεδομένα αυτής της συσκευής θα διαγραφούν οριστικά.", "Διαγραφή λογαριασμού", "Αποσύνδεση και επαναφορά συσκευής;", "Όλη η πρόοδος και οι προτιμήσεις αυτής της συσκευής θα διαγραφούν. Η συγχρονισμένη πρόοδος στο cloud θα παραμείνει."],
};

export function featureCopy(lang: LangCode): FeatureCopy {
  const row = rows[lang];
  if (row.length !== keys.length) throw new Error(`Incomplete feature copy for ${lang}`);
  return Object.fromEntries(keys.map((key, index) => [key, row[index]])) as FeatureCopy;
}
