import type { LangCode } from "./i18n";

export type PremiumCopy = {
  close: string; lifetime: string; prepare: string; intro: string; active: string;
  included: string; benefits: string; continuePurchase: string; loginNote: string;
  storeSetup: string; loadingPrice: string; unlock: string; unavailable: string;
  restoring: string; restore: string; checking: string; cancelled: string;
  purchaseFailed: string; noPrevious: string; restoreFailed: string;
};
const keys: (keyof PremiumCopy)[] = ["close","lifetime","prepare","intro","active","included","benefits","continuePurchase","loginNote","storeSetup","loadingPrice","unlock","unavailable","restoring","restore","checking","cancelled","purchaseFailed","noPrevious","restoreFailed"];
const rows: Record<LangCode, string[]> = {
  de:["Premium schließen","Lebenslanger Zugriff","Sicher vorbereitet","Ein einmaliger Kauf schaltet Premium dauerhaft frei – ohne Abo und wiederkehrende Kosten.","Premium ist für dieses Konto aktiv.","Alles in Premium","Übersetzte Erklärungen, Aussprache-Audio, gezieltes Üben schwacher Themen, unbegrenzte Probeprüfungen, ausführliche Lernanalyse, Cloud-Synchronisierung, persönlicher Lernplan und keine Werbung.","Zum einmaligen Kauf","Melde dich an oder erstelle ein Konto, damit dein Kauf gesichert und wiederhergestellt werden kann. Kostenloses Lernen bleibt ohne Konto möglich.","Die Käufe sind vorbereitet, benötigen aber noch die öffentlichen RevenueCat-SDK-Schlüssel.","Preis wird geladen …","Dauerhaft freischalten — {price}","Lebenslanger Kauf nicht verfügbar","Wird wiederhergestellt …","Käufe wiederherstellen","Premium-Zugriff wird geprüft …","Kauf abgebrochen. Es wurde nichts berechnet.","Der Kauf konnte nicht abgeschlossen werden.","Für dieses Store-Konto wurde kein früherer Premium-Kauf gefunden.","Käufe konnten nicht wiederhergestellt werden."],
  en:["Close Premium","Lifetime access","Prepare with confidence","One purchase unlocks Premium permanently—no subscription or recurring charge.","Premium is active on this account.","Everything in Premium","Translated explanations, pronunciation audio, targeted weak-topic practice, unlimited mock exams, detailed analytics, cloud sync, a personal study plan, and no ads.","Continue to one-time purchase","Log in or create an account to secure and restore your purchase. Free study remains available without an account.","Purchases are ready but still require the public RevenueCat SDK keys.","Loading price…","Unlock forever — {price}","Lifetime purchase unavailable","Restoring…","Restore purchases","Checking Premium access…","Purchase cancelled. No charge was made.","The purchase could not be completed.","No previous Premium purchase was found for this store account.","Purchases could not be restored."],
  tr:["Premium'u kapat","Ömür boyu erişim","Güvenle hazırlanın","Tek seferlik satın alma Premium'u kalıcı olarak açar; abonelik ve yinelenen ücret yoktur.","Premium bu hesapta etkin.","Premium'daki her şey","Çevrilmiş açıklamalar, telaffuz sesi, zayıf konulara yönelik çalışma, sınırsız deneme sınavı, ayrıntılı analiz, bulut eşitleme, kişisel çalışma planı ve reklamsız kullanım.","Tek seferlik satın almaya devam et","Satın almayı güvenceye almak ve geri yüklemek için giriş yapın veya hesap oluşturun. Ücretsiz çalışma hesapsız da kullanılabilir.","Satın alma hazır, ancak herkese açık RevenueCat SDK anahtarları gerekiyor.","Fiyat yükleniyor…","Kalıcı olarak aç — {price}","Ömür boyu satın alma kullanılamıyor","Geri yükleniyor…","Satın alımları geri yükle","Premium erişimi denetleniyor…","Satın alma iptal edildi. Ücret alınmadı.","Satın alma tamamlanamadı.","Bu mağaza hesabında önceki Premium satın alımı bulunamadı.","Satın alımlar geri yüklenemedi."],
  ru:["Закрыть Premium","Пожизненный доступ","Готовьтесь уверенно","Одна покупка навсегда открывает Premium — без подписки и повторных платежей.","Premium активен для этого аккаунта.","Всё в Premium","Переведённые объяснения, озвучивание, тренировка слабых тем, неограниченные пробные экзамены, подробная аналитика, облачная синхронизация, личный план и отсутствие рекламы.","Перейти к разовой покупке","Войдите или создайте аккаунт, чтобы защитить и восстановить покупку. Бесплатное обучение доступно без аккаунта.","Покупки готовы, но нужны открытые SDK-ключи RevenueCat.","Загрузка цены…","Открыть навсегда — {price}","Пожизненная покупка недоступна","Восстановление…","Восстановить покупки","Проверка доступа Premium…","Покупка отменена. Плата не списана.","Не удалось завершить покупку.","Для этого аккаунта магазина прежняя покупка Premium не найдена.","Не удалось восстановить покупки."],
  uk:["Закрити Premium","Довічний доступ","Готуйтеся впевнено","Одна покупка назавжди відкриває Premium — без підписки та повторних платежів.","Premium активний для цього облікового запису.","Усе в Premium","Перекладені пояснення, озвучення, тренування слабких тем, необмежені пробні іспити, детальна аналітика, хмарна синхронізація, особистий план і без реклами.","Перейти до разової покупки","Увійдіть або створіть обліковий запис, щоб захистити й відновити покупку. Безкоштовне навчання доступне без облікового запису.","Покупки готові, але потрібні публічні SDK-ключі RevenueCat.","Завантаження ціни…","Відкрити назавжди — {price}","Довічна покупка недоступна","Відновлення…","Відновити покупки","Перевірка доступу Premium…","Покупку скасовано. Кошти не списано.","Не вдалося завершити покупку.","Для цього облікового запису магазину попередню покупку Premium не знайдено.","Не вдалося відновити покупки."],
  ar:["إغلاق بريميوم","وصول مدى الحياة","استعد بثقة","عملية شراء واحدة تفتح بريميوم نهائيًا، بلا اشتراك أو رسوم متكررة.","بريميوم مفعّل لهذا الحساب.","كل ما يتضمنه بريميوم","شروح مترجمة، وصوت للنطق، وتدريب على الموضوعات الضعيفة، واختبارات تجريبية غير محدودة، وتحليلات مفصلة، ومزامنة سحابية، وخطة دراسة شخصية، ومن دون إعلانات.","المتابعة إلى الشراء لمرة واحدة","سجّل الدخول أو أنشئ حسابًا لحفظ عملية الشراء واستعادتها. تظل الدراسة المجانية متاحة بلا حساب.","عمليات الشراء جاهزة، لكنها تحتاج إلى مفاتيح RevenueCat SDK العامة.","جارٍ تحميل السعر…","فتح دائم — {price}","الشراء مدى الحياة غير متاح","جارٍ الاستعادة…","استعادة المشتريات","جارٍ التحقق من وصول بريميوم…","أُلغيت عملية الشراء ولم تُفرض رسوم.","تعذر إكمال عملية الشراء.","لم يُعثر على عملية شراء سابقة لبريميوم في حساب المتجر هذا.","تعذرت استعادة المشتريات."],
  fr:["Fermer Premium","Accès à vie","Préparez-vous sereinement","Un achat unique débloque Premium définitivement, sans abonnement ni frais récurrents.","Premium est actif sur ce compte.","Tout dans Premium","Explications traduites, audio de prononciation, travail ciblé des points faibles, examens blancs illimités, analyses détaillées, synchronisation cloud, plan personnel et aucune publicité.","Continuer vers l’achat unique","Connectez-vous ou créez un compte pour sécuriser et restaurer votre achat. L’étude gratuite reste accessible sans compte.","Les achats sont prêts, mais nécessitent encore les clés SDK publiques RevenueCat.","Chargement du prix…","Débloquer à vie — {price}","Achat à vie indisponible","Restauration…","Restaurer les achats","Vérification de l’accès Premium…","Achat annulé. Aucun montant débité.","L’achat n’a pas pu être effectué.","Aucun achat Premium antérieur trouvé pour ce compte de boutique.","Impossible de restaurer les achats."],
  hi:["प्रीमियम बंद करें","आजीवन पहुँच","आत्मविश्वास से तैयारी करें","एक बार की खरीद प्रीमियम को हमेशा के लिए खोलती है—कोई सदस्यता या आवर्ती शुल्क नहीं।","इस खाते पर प्रीमियम सक्रिय है।","प्रीमियम में सब कुछ","अनूदित व्याख्याएँ, उच्चारण ऑडियो, कमजोर विषयों का अभ्यास, असीमित अभ्यास परीक्षाएँ, विस्तृत विश्लेषण, क्लाउड सिंक, व्यक्तिगत अध्ययन योजना और विज्ञापन-मुक्त उपयोग।","एकमुश्त खरीद जारी रखें","खरीद सुरक्षित रखने और पुनर्स्थापित करने के लिए लॉग इन करें या खाता बनाएँ। निःशुल्क अध्ययन बिना खाते के उपलब्ध है।","खरीद तैयार है, लेकिन सार्वजनिक RevenueCat SDK कुंजियाँ अभी आवश्यक हैं।","मूल्य लोड हो रहा है…","हमेशा के लिए खोलें — {price}","आजीवन खरीद उपलब्ध नहीं","पुनर्स्थापित हो रहा है…","खरीद पुनर्स्थापित करें","प्रीमियम पहुँच जाँची जा रही है…","खरीद रद्द हुई। कोई शुल्क नहीं लगा।","खरीद पूरी नहीं हो सकी।","इस स्टोर खाते के लिए पिछली प्रीमियम खरीद नहीं मिली।","खरीद पुनर्स्थापित नहीं हो सकी।"],
  pl:["Zamknij Premium","Dostęp dożywotni","Przygotuj się z pewnością","Jednorazowy zakup odblokowuje Premium na zawsze — bez abonamentu i opłat cyklicznych.","Premium jest aktywne na tym koncie.","Wszystko w Premium","Przetłumaczone wyjaśnienia, nagrania wymowy, ćwiczenie słabych tematów, nielimitowane egzaminy próbne, szczegółowa analiza, synchronizacja w chmurze, osobisty plan nauki i brak reklam.","Przejdź do jednorazowego zakupu","Zaloguj się lub utwórz konto, aby zabezpieczyć i przywracać zakup. Bezpłatna nauka pozostaje dostępna bez konta.","Zakupy są przygotowane, ale nadal wymagają publicznych kluczy SDK RevenueCat.","Ładowanie ceny…","Odblokuj na zawsze — {price}","Zakup dożywotni niedostępny","Przywracanie…","Przywróć zakupy","Sprawdzanie dostępu Premium…","Zakup anulowany. Nie pobrano opłaty.","Nie udało się sfinalizować zakupu.","Nie znaleziono wcześniejszego zakupu Premium dla tego konta sklepu.","Nie udało się przywrócić zakupów."],
  ro:["Închideți Premium","Acces pe viață","Pregătiți-vă cu încredere","O singură achiziție deblochează Premium definitiv, fără abonament sau taxe recurente.","Premium este activ pe acest cont.","Totul în Premium","Explicații traduse, pronunție audio, exersarea punctelor slabe, examene simulate nelimitate, analiză detaliată, sincronizare cloud, plan personal și fără reclame.","Continuați la achiziția unică","Autentificați-vă sau creați un cont pentru a proteja și restaura achiziția. Studiul gratuit rămâne disponibil fără cont.","Achizițiile sunt pregătite, dar necesită cheile SDK publice RevenueCat.","Se încarcă prețul…","Deblocați definitiv — {price}","Achiziția pe viață nu este disponibilă","Se restaurează…","Restaurați achizițiile","Se verifică accesul Premium…","Achiziție anulată. Nu s-a perceput nicio taxă.","Achiziția nu a putut fi finalizată.","Nu s-a găsit nicio achiziție Premium anterioară pentru acest cont de magazin.","Achizițiile nu au putut fi restaurate."],
  fa:["بستن پریمیوم","دسترسی مادام‌العمر","با اطمینان آماده شوید","با یک خرید، پریمیوم برای همیشه و بدون اشتراک یا هزینهٔ تکراری فعال می‌شود.","پریمیوم برای این حساب فعال است.","همه‌چیز در پریمیوم","توضیح‌های ترجمه‌شده، صدای تلفظ، تمرین هدفمند موضوعات ضعیف، آزمون نامحدود، تحلیل دقیق، همگام‌سازی ابری، برنامهٔ شخصی و بدون تبلیغ.","ادامه به خرید یک‌باره","برای حفظ و بازیابی خرید وارد شوید یا حساب بسازید. مطالعهٔ رایگان بدون حساب نیز در دسترس است.","خرید آماده است، اما هنوز کلیدهای عمومی RevenueCat SDK لازم است.","در حال بارگیری قیمت…","فعال‌سازی همیشگی — {price}","خرید مادام‌العمر در دسترس نیست","در حال بازیابی…","بازیابی خریدها","بررسی دسترسی پریمیوم…","خرید لغو شد و هزینه‌ای دریافت نشد.","خرید تکمیل نشد.","خرید قبلی پریمیوم برای این حساب فروشگاه پیدا نشد.","خریدها بازیابی نشدند."],
  ur:["پریمیم بند کریں","تاحیات رسائی","اعتماد کے ساتھ تیاری کریں","ایک بار کی خرید پریمیم کو ہمیشہ کے لیے کھولتی ہے، بغیر رکنیت یا بار بار فیس کے۔","اس اکاؤنٹ پر پریمیم فعال ہے۔","پریمیم میں سب کچھ","ترجمہ شدہ وضاحتیں، تلفظ کی آڈیو، کمزور موضوعات کی مشق، لامحدود آزمائشی امتحان، تفصیلی تجزیہ، کلاؤڈ ہم آہنگی، ذاتی منصوبہ اور اشتہارات کے بغیر استعمال۔","ایک بار کی خرید جاری رکھیں","خرید محفوظ رکھنے اور بحال کرنے کے لیے لاگ اِن کریں یا اکاؤنٹ بنائیں۔ مفت مطالعہ بغیر اکاؤنٹ بھی دستیاب ہے۔","خریداری تیار ہے مگر عوامی RevenueCat SDK کلیدیں درکار ہیں۔","قیمت لوڈ ہو رہی ہے…","ہمیشہ کے لیے کھولیں — {price}","تاحیات خرید دستیاب نہیں","بحال ہو رہا ہے…","خرید بحال کریں","پریمیم رسائی چیک ہو رہی ہے…","خرید منسوخ ہوئی۔ کوئی رقم نہیں لی گئی۔","خرید مکمل نہ ہو سکی۔","اس اسٹور اکاؤنٹ پر پچھلی پریمیم خرید نہیں ملی۔","خرید بحال نہ ہو سکی۔"],
  sq:["Mbyll Premium","Qasje e përhershme","Përgatituni me siguri","Një blerje e vetme e zhbllokon Premium përgjithmonë, pa abonim ose pagesa të përsëritura.","Premium është aktiv në këtë llogari.","Gjithçka në Premium","Shpjegime të përkthyera, audio shqiptimi, ushtrime për temat e dobëta, provime model pa kufi, analizë e hollësishme, sinkronizim në re, plan personal dhe pa reklama.","Vazhdo te blerja njëherëshe","Hyni ose krijoni llogari për ta ruajtur dhe rikthyer blerjen. Mësimi falas mbetet pa llogari.","Blerjet janë gati, por kërkojnë çelësat publikë RevenueCat SDK.","Po ngarkohet çmimi…","Zhblloko përgjithmonë — {price}","Blerja e përhershme nuk ofrohet","Po rikthehet…","Rikthe blerjet","Po kontrollohet qasja Premium…","Blerja u anulua. Nuk u tarifuat.","Blerja nuk u përfundua.","Nuk u gjet blerje e mëparshme Premium për këtë llogari dyqani.","Blerjet nuk u rikthyen."],
  bs:["Zatvori Premium","Doživotni pristup","Pripremite se sa sigurnošću","Jedna kupovina trajno otključava Premium, bez pretplate i ponavljajućih naknada.","Premium je aktivan na ovom računu.","Sve u Premiumu","Prevedena objašnjenja, izgovor, ciljane vježbe slabih tema, neograničeni probni ispiti, detaljna analiza, sinhronizacija u oblaku, lični plan i bez oglasa.","Nastavi na jednokratnu kupovinu","Prijavite se ili napravite račun kako biste sačuvali i obnovili kupovinu. Besplatno učenje ostaje dostupno bez računa.","Kupovine su spremne, ali zahtijevaju javne RevenueCat SDK ključeve.","Učitavanje cijene…","Otključaj zauvijek — {price}","Doživotna kupovina nije dostupna","Obnavljanje…","Obnovi kupovine","Provjera Premium pristupa…","Kupovina je otkazana. Nije naplaćeno.","Kupovina nije mogla biti završena.","Nije pronađena ranija Premium kupovina za ovaj račun trgovine.","Kupovine nisu mogle biti obnovljene."],
  bg:["Затваряне на Premium","Доживотен достъп","Подгответе се уверено","Една покупка отключва Premium завинаги, без абонамент и повтарящи се такси.","Premium е активен за този профил.","Всичко в Premium","Преведени обяснения, аудио произношение, упражнения по слабите теми, неограничени пробни изпити, подробен анализ, облачна синхронизация, личен план и без реклами.","Към еднократната покупка","Влезте или създайте профил, за да защитите и възстановявате покупката. Безплатното учене остава достъпно без профил.","Покупките са готови, но изискват публичните RevenueCat SDK ключове.","Зареждане на цената…","Отключване завинаги — {price}","Доживотната покупка не е налична","Възстановяване…","Възстановяване на покупки","Проверка на Premium достъпа…","Покупката е отменена. Няма таксуване.","Покупката не можа да завърши.","Не е намерена предишна Premium покупка за този магазинен профил.","Покупките не можаха да бъдат възстановени."],
  it:["Chiudi Premium","Accesso a vita","Preparati con sicurezza","Un unico acquisto sblocca Premium per sempre, senza abbonamento o costi ricorrenti.","Premium è attivo su questo account.","Tutto in Premium","Spiegazioni tradotte, audio della pronuncia, esercizi sui punti deboli, simulazioni illimitate, analisi dettagliate, sincronizzazione cloud, piano personale e nessuna pubblicità.","Continua all’acquisto una tantum","Accedi o crea un account per proteggere e ripristinare l’acquisto. Lo studio gratuito resta disponibile senza account.","Gli acquisti sono pronti, ma richiedono le chiavi SDK pubbliche RevenueCat.","Caricamento prezzo…","Sblocca per sempre — {price}","Acquisto a vita non disponibile","Ripristino…","Ripristina acquisti","Verifica accesso Premium…","Acquisto annullato. Nessun addebito.","Non è stato possibile completare l’acquisto.","Nessun precedente acquisto Premium trovato per questo account dello store.","Non è stato possibile ripristinare gli acquisti."],
  zh:["关闭高级版","终身使用","安心备考","一次购买即可永久解锁高级版，无订阅，也无重复收费。","此账户已启用高级版。","高级版全部功能","翻译讲解、发音音频、薄弱主题专项练习、无限模拟考试、详细分析、云同步、个人学习计划以及无广告体验。","继续一次性购买","请登录或创建账户，以便保护和恢复购买。无需账户也可继续免费学习。","购买功能已就绪，但仍需配置 RevenueCat 公共 SDK 密钥。","正在加载价格…","永久解锁 — {price}","暂时无法购买终身版","正在恢复…","恢复购买","正在检查高级版权限…","购买已取消，未产生费用。","无法完成购买。","未在此商店账户中找到以前的高级版购买记录。","无法恢复购买。"],
  el:["Κλείσιμο Premium","Ισόβια πρόσβαση","Προετοιμαστείτε με σιγουριά","Μία αγορά ξεκλειδώνει μόνιμα το Premium, χωρίς συνδρομή ή επαναλαμβανόμενη χρέωση.","Το Premium είναι ενεργό σε αυτόν τον λογαριασμό.","Όλα στο Premium","Μεταφρασμένες επεξηγήσεις, ήχος προφοράς, εξάσκηση αδύναμων θεμάτων, απεριόριστες προσομοιώσεις, λεπτομερή αναλυτικά στοιχεία, συγχρονισμός cloud, προσωπικό πλάνο και χωρίς διαφημίσεις.","Συνέχεια στην εφάπαξ αγορά","Συνδεθείτε ή δημιουργήστε λογαριασμό για να ασφαλίσετε και να επαναφέρετε την αγορά. Η δωρεάν μελέτη παραμένει διαθέσιμη χωρίς λογαριασμό.","Οι αγορές είναι έτοιμες, αλλά χρειάζονται τα δημόσια κλειδιά RevenueCat SDK.","Φόρτωση τιμής…","Μόνιμο ξεκλείδωμα — {price}","Η ισόβια αγορά δεν είναι διαθέσιμη","Επαναφορά…","Επαναφορά αγορών","Έλεγχος πρόσβασης Premium…","Η αγορά ακυρώθηκε. Δεν έγινε χρέωση.","Η αγορά δεν ολοκληρώθηκε.","Δεν βρέθηκε προηγούμενη αγορά Premium για αυτόν τον λογαριασμό καταστήματος.","Δεν ήταν δυνατή η επαναφορά αγορών."],
};
export function premiumCopy(lang: LangCode): PremiumCopy {
  const row = rows[lang];
  if (row.length !== keys.length) throw new Error(`Incomplete Premium copy for ${lang}`);
  return Object.fromEntries(keys.map((key, i) => [key, row[i]])) as PremiumCopy;
}
