import type { LangCode } from "./i18n";

export type StudyCopy = {
  freeExamsUsed: string; seePremium: string; submitTitle: string; unanswered: string;
  keepEditing: string; passSummary: string; correctAnswer: string; explanation: string;
  explain: string; premiumExplanation: string; premiumAudio: string; stopAudio: string; playAudio: string;
  chooseQuestion: string; closePicker: string; close: string; finish: string;
  sessionComplete: string; viewAnalytics: string; anotherSession: string; results: string;
};

const keys: (keyof StudyCopy)[] = ["freeExamsUsed","seePremium","submitTitle","unanswered","keepEditing","passSummary","correctAnswer","explanation","explain","premiumExplanation","premiumAudio","stopAudio","playAudio","chooseQuestion","closePicker","close","finish","sessionComplete","viewAnalytics","anotherSession","results"];
const rows: Record<LangCode, string[]> = {
  de:["Du hast alle {n} kostenlosen Probeprüfungen genutzt. Premium enthält unbegrenzt viele Probeprüfungen.","Premium ansehen","Prüfung abgeben?","Noch nicht beantwortet: {n}","Weiter bearbeiten","Zum Bestehen sind 17 von 33 richtigen Antworten nötig.","RICHTIGE ANTWORT","Erklärung","Erklären","Premium-Erklärung","Premium-Audio","Vorlesen beenden","Vorlesen","Frage auswählen","Fragenauswahl schließen","Schließen","Fertig","Übung abgeschlossen","Aktualisierte Analyse ansehen","Weitere Schwerpunktübung starten","Ergebnis"],
  en:["You have used all {n} free mock exams. Premium includes unlimited mock exams.","See Premium","Submit exam?","Not answered yet: {n}","Keep editing","You need 17 correct answers out of 33 to pass.","CORRECT ANSWER","Explanation","Explain","Premium explanation","Premium audio","Stop reading aloud","Read aloud","Choose a question","Close question picker","Close","Finish","Session complete","View updated analytics","Start another focused session","Results"],
  tr:["{n} ücretsiz deneme sınavının tümünü kullandınız. Premium sınırsız deneme sınavı sunar.","Premium'u gör","Sınav gönderilsin mi?","Henüz cevaplanmadı: {n}","Düzenlemeye devam et","Geçmek için 33 sorudan 17'sini doğru cevaplamalısınız.","DOĞRU CEVAP","Açıklama","Açıkla","Premium açıklaması","Premium ses","Sesli okumayı durdur","Sesli oku","Soru seç","Soru seçiciyi kapat","Kapat","Bitir","Oturum tamamlandı","Güncel analizi gör","Yeni odaklı oturum başlat","Sonuçlar"],
  ru:["Вы использовали все бесплатные пробные экзамены ({n}). В Premium их количество не ограничено.","Посмотреть Premium","Завершить экзамен?","Без ответа: {n}","Продолжить","Для сдачи нужно 17 правильных ответов из 33.","ПРАВИЛЬНЫЙ ОТВЕТ","Объяснение","Объяснить","Объяснение Premium","Аудио Premium","Остановить чтение","Прочитать вслух","Выбрать вопрос","Закрыть выбор вопросов","Закрыть","Готово","Занятие завершено","Открыть обновлённую аналитику","Начать ещё одно занятие","Результаты"],
  uk:["Ви використали всі безкоштовні пробні іспити ({n}). Premium надає необмежену кількість.","Переглянути Premium","Завершити іспит?","Без відповіді: {n}","Продовжити","Для складання потрібно 17 правильних відповідей із 33.","ПРАВИЛЬНА ВІДПОВІДЬ","Пояснення","Пояснити","Пояснення Premium","Аудіо Premium","Зупинити читання","Прочитати вголос","Вибрати запитання","Закрити вибір запитань","Закрити","Готово","Заняття завершено","Переглянути оновлену аналітику","Почати ще одне заняття","Результати"],
  ar:["لقد استخدمت الاختبارات التجريبية المجانية وعددها {n}. يوفّر بريميوم اختبارات غير محدودة.","عرض بريميوم","إرسال الاختبار؟","من دون إجابة: {n}","متابعة التعديل","تحتاج إلى 17 إجابة صحيحة من أصل 33 للنجاح.","الإجابة الصحيحة","الشرح","شرح","شرح بريميوم","صوت بريميوم","إيقاف القراءة","القراءة بصوت عالٍ","اختيار سؤال","إغلاق منتقي الأسئلة","إغلاق","إنهاء","اكتملت الجلسة","عرض التحليلات المحدّثة","بدء جلسة مركّزة أخرى","النتائج"],
  fr:["Vous avez utilisé les {n} examens blancs gratuits. Premium offre des examens blancs illimités.","Voir Premium","Valider l’examen ?","Sans réponse : {n}","Continuer à modifier","Il faut 17 bonnes réponses sur 33 pour réussir.","BONNE RÉPONSE","Explication","Expliquer","Explication Premium","Audio Premium","Arrêter la lecture","Lire à voix haute","Choisir une question","Fermer le sélecteur","Fermer","Terminer","Session terminée","Voir l’analyse actualisée","Démarrer une autre session ciblée","Résultats"],
  hi:["आप सभी {n} निःशुल्क अभ्यास परीक्षाएँ उपयोग कर चुके हैं। प्रीमियम में असीमित परीक्षाएँ हैं।","प्रीमियम देखें","परीक्षा जमा करें?","बिना उत्तर: {n}","संपादन जारी रखें","उत्तीर्ण होने के लिए 33 में से 17 सही उत्तर चाहिए।","सही उत्तर","व्याख्या","समझाएँ","प्रीमियम व्याख्या","प्रीमियम ऑडियो","पढ़ना रोकें","ज़ोर से पढ़ें","प्रश्न चुनें","प्रश्न चयन बंद करें","बंद करें","समाप्त","सत्र पूरा हुआ","नया विश्लेषण देखें","एक और केंद्रित सत्र शुरू करें","परिणाम"],
  pl:["Wykorzystano wszystkie bezpłatne egzaminy próbne ({n}). Premium oferuje ich bez limitu.","Zobacz Premium","Zakończyć egzamin?","Bez odpowiedzi: {n}","Kontynuuj edycję","Aby zdać, trzeba poprawnie odpowiedzieć na 17 z 33 pytań.","POPRAWNA ODPOWIEDŹ","Wyjaśnienie","Wyjaśnij","Wyjaśnienie Premium","Dźwięk Premium","Zatrzymaj czytanie","Czytaj na głos","Wybierz pytanie","Zamknij wybór pytań","Zamknij","Zakończ","Sesja ukończona","Zobacz zaktualizowaną analizę","Rozpocznij kolejną sesję","Wyniki"],
  ro:["Ați folosit toate cele {n} examene simulate gratuite. Premium oferă examene nelimitate.","Vedeți Premium","Trimiteți examenul?","Fără răspuns: {n}","Continuați editarea","Pentru promovare sunt necesare 17 răspunsuri corecte din 33.","RĂSPUNS CORECT","Explicație","Explicați","Explicație Premium","Audio Premium","Opriți citirea","Citiți cu voce tare","Alegeți o întrebare","Închideți selectorul","Închideți","Finalizați","Sesiune încheiată","Vedeți analiza actualizată","Începeți altă sesiune focalizată","Rezultate"],
  fa:["همهٔ {n} آزمون آزمایشی رایگان را استفاده کرده‌اید. پریمیوم آزمون نامحدود دارد.","مشاهدهٔ پریمیوم","آزمون ارسال شود؟","بی‌پاسخ: {n}","ادامهٔ ویرایش","برای قبولی به ۱۷ پاسخ درست از ۳۳ نیاز دارید.","پاسخ درست","توضیح","توضیح","توضیح پریمیوم","صدای پریمیوم","توقف خواندن","بلندخوانی","انتخاب پرسش","بستن انتخابگر پرسش","بستن","پایان","جلسه کامل شد","مشاهدهٔ تحلیل به‌روز","شروع یک جلسهٔ متمرکز دیگر","نتایج"],
  ur:["آپ تمام {n} مفت آزمائشی امتحان استعمال کر چکے ہیں۔ پریمیم میں لامحدود امتحان ہیں۔","پریمیم دیکھیں","امتحان جمع کریں؟","بغیر جواب: {n}","ترمیم جاری رکھیں","کامیابی کے لیے 33 میں سے 17 درست جواب درکار ہیں۔","درست جواب","وضاحت","وضاحت کریں","پریمیم وضاحت","پریمیم آڈیو","پڑھنا روکیں","بلند آواز سے پڑھیں","سوال منتخب کریں","سوال چننے والا بند کریں","بند کریں","مکمل","سیشن مکمل","تازہ تجزیہ دیکھیں","ایک اور مرکوز سیشن شروع کریں","نتائج"],
  sq:["I keni përdorur të {n} provimet model falas. Premium ofron provime pa kufi.","Shiko Premium","Të dorëzohet provimi?","Pa përgjigje: {n}","Vazhdo redaktimin","Për të kaluar duhen 17 përgjigje të sakta nga 33.","PËRGJIGJJA E SAKTË","Shpjegim","Shpjego","Shpjegim Premium","Audio Premium","Ndalo leximin","Lexo me zë","Zgjidh një pyetje","Mbyll përzgjedhësin","Mbyll","Përfundo","Seanca përfundoi","Shiko analizën e përditësuar","Fillo një seancë tjetër të fokusuar","Rezultatet"],
  bs:["Iskoristili ste svih {n} besplatnih probnih ispita. Premium nudi neograničene ispite.","Pogledaj Premium","Predati ispit?","Bez odgovora: {n}","Nastavi uređivanje","Za prolaz je potrebno 17 tačnih odgovora od 33.","TAČAN ODGOVOR","Objašnjenje","Objasni","Premium objašnjenje","Premium zvuk","Zaustavi čitanje","Čitaj naglas","Odaberi pitanje","Zatvori izbor pitanja","Zatvori","Završi","Sesija završena","Pogledaj ažuriranu analizu","Pokreni novu ciljanu sesiju","Rezultati"],
  bg:["Използвахте всички {n} безплатни пробни изпита. Premium предлага неограничени изпити.","Вижте Premium","Предаване на изпита?","Без отговор: {n}","Продължаване","За успешно полагане са нужни 17 верни отговора от 33.","ВЕРЕН ОТГОВОР","Обяснение","Обясни","Premium обяснение","Premium аудио","Спиране на четенето","Прочети на глас","Изберете въпрос","Затворете избора","Затвори","Край","Сесията приключи","Вижте обновения анализ","Започнете друга целева сесия","Резултати"],
  it:["Hai utilizzato tutti i {n} esami simulati gratuiti. Premium offre esami illimitati.","Vedi Premium","Consegnare l’esame?","Senza risposta: {n}","Continua a modificare","Per superare l’esame servono 17 risposte corrette su 33.","RISPOSTA CORRETTA","Spiegazione","Spiega","Spiegazione Premium","Audio Premium","Interrompi lettura","Leggi ad alta voce","Scegli una domanda","Chiudi selettore domande","Chiudi","Fine","Sessione completata","Vedi analisi aggiornata","Avvia un’altra sessione mirata","Risultati"],
  zh:["您已用完 {n} 次免费模拟考试。高级版可无限次参加模拟考试。","查看高级版","提交考试？","未作答：{n}","继续作答","答对 33 题中的 17 题即可通过。","正确答案","解释","解释","高级版解释","高级版音频","停止朗读","朗读","选择题目","关闭题目选择器","关闭","完成","练习已完成","查看最新分析","开始另一轮专项练习","结果"],
  el:["Χρησιμοποιήσατε και τις {n} δωρεάν προσομοιώσεις. Το Premium προσφέρει απεριόριστες.","Προβολή Premium","Υποβολή εξέτασης;","Χωρίς απάντηση: {n}","Συνέχεια επεξεργασίας","Χρειάζονται 17 σωστές απαντήσεις στις 33 για επιτυχία.","ΣΩΣΤΗ ΑΠΑΝΤΗΣΗ","Επεξήγηση","Επεξήγηση","Επεξήγηση Premium","Ήχος Premium","Διακοπή ανάγνωσης","Ανάγνωση δυνατά","Επιλογή ερώτησης","Κλείσιμο επιλογέα","Κλείσιμο","Τέλος","Η συνεδρία ολοκληρώθηκε","Προβολή ενημερωμένης ανάλυσης","Έναρξη άλλης εστιασμένης συνεδρίας","Αποτελέσματα"],
};

export function studyCopy(lang: LangCode): StudyCopy {
  const row = rows[lang];
  if (row.length !== keys.length) throw new Error(`Incomplete study copy for ${lang}`);
  return Object.fromEntries(keys.map((key, i) => [key, row[i]])) as StudyCopy;
}
