"""Trim data/questions.json into the asset the app bundles.

Drops the provenance fields the app does not need (sources, scores, page) and
groups the state questions, so the bundle stays small.

    python tools/export_app_data.py
    -> mobile/assets/questions.json
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "questions.json"
IMAGES = ROOT / "data" / "images.json"
OUT = ROOT / "mobile" / "assets" / "questions.json"
IMAGE_MAP = ROOT / "mobile" / "src" / "imageMap.ts"


def write_image_map(files):
    """Metro resolves require() statically, so dynamic paths cannot be used.
    Generate the lookup instead of maintaining it by hand."""
    lines = [
        "// Generated by tools/export_app_data.py — do not edit.",
        "import type { ImageSourcePropType } from \"react-native\";",
        "",
        "export const images: Record<string, ImageSourcePropType> = {",
    ]
    for name in sorted(files):
        lines.append(f'  "{name}": require("../assets/images/{name}"),')
    lines += ["};", ""]
    IMAGE_MAP.parent.mkdir(parents=True, exist_ok=True)
    IMAGE_MAP.write_text("\n".join(lines), encoding="utf8")


def main():
    questions = json.loads(SRC.read_text(encoding="utf8"))
    bindings = json.loads(IMAGES.read_text(encoding="utf8")) if IMAGES.exists() else {}

    bundled = set()
    for entry in bindings.values():
        if not entry["restricted"]:
            bundled.update(entry["files"])
    write_image_map(bundled)

    def media(q):
        entry = bindings.get(q["id"])
        if not entry:
            return None
        # licensed press photos are described rather than shown
        files = [] if entry["restricted"] else entry["files"]
        return {"kind": entry["kind"], "files": files, "alt": entry["alt"]}

    payload = {
        "version": "2025-05-07",  # Stand of the BAMF catalogue
        "questions": [
            {
                "id": q["id"],
                "scope": q["scope"],
                "question": q["question"],
                "options": q["options"],
                "answer": q["answer"],
                "image": q["imageQuestion"],
                "verified": q["verified"],
                **({"tr": q["translations"]} if q.get("translations") else {}),
                **({"media": m} if (m := media(q)) else {}),
            }
            for q in questions
        ],
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, ensure_ascii=False, separators=(",", ":")), encoding="utf8")

    states = sorted({q["scope"] for q in questions} - {"ALL"})
    kb = OUT.stat().st_size / 1024
    with_media = sum(1 for q in payload["questions"] if "media" in q)
    described = sum(1 for q in payload["questions"] if q.get("media") and not q["media"]["files"])
    print(f"{len(payload['questions'])} questions -> {OUT.relative_to(ROOT)} ({kb:.0f} KB)")
    print(f"  general: {sum(1 for q in questions if q['scope'] == 'ALL')}")
    print(f"  states : {len(states)}")
    print(f"  with media : {with_media}  (of which text-described only: {described})")
    print(f"  image map  : {len(bundled)} files -> {IMAGE_MAP.relative_to(ROOT)}")
    print(f"  unverified answers shipped: {sum(1 for q in questions if not q['verified'])}")


if __name__ == "__main__":
    main()
